# Generated by Django 5.1.2 on 2024-10-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={
                "ordering": ("model",),
                "verbose_name": "car",
                "verbose_name_plural": "cars",
            },
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": ("username",),
                "verbose_name": "driver",
                "verbose_name_plural": "drivers",
            },
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={
                "ordering": ("name",),
                "verbose_name": "manufacturer",
                "verbose_name_plural": "manufacturers",
            },
        ),
    ]
